### ISSUE TITLE
[Bug] package.json 충돌

### ISSUE THREAD

**Issue by jizerozz** [Dev-FE-1/Toy_Project_II_team4#21]
### 🐞 설명

버튼 컴포넌트에와 datepicker 작업하면서 추가한 라이브러리가 기존 main 브랜치의 packgae.json에 없어서 충돌 발생

### 💻 버그 시뮬레이션

![image](https://github.com/user-attachments/assets/fa0c1645-cd45-4e95-ae90-5ae6a3b06664)

**Comment by nakyeonko3** [comment]
엇 이러면 datepicker 라이브러리가 있는 package.json을 살리는 쪽으로 컨플릭 해결하시면 될것 같습니다. 
컨플릭난 main의 package.json은 지우고 새 package.json 적용해도 될 것 같아요.

**Comment by jizerozz** [comment]
오 엄청 빠르게 답글 남겨주셨네요 감사합니다 낙연님 일단 컨플릭 해결은 했는데 각 컴포넌트 파일들을 열어보니 esLint 관련 에러가 나는데 이건 제 환경 문제일까요?

**Comment by jizerozz** [comment]
> 엇 이러면 datepicker 라이브러리가 있는 package.json을 살리는 쪽으로 컨플릭 해결하시면 될것 같습니다. 컨플릭난 main의 package.json은 지우고 새 package.json 적용해도 될 것 같아요.

오 엄청 빠르게 답글 남겨주셨네요 감사합니다 낙연님 일단 컨플릭 해결은 했는데 각 컴포넌트 파일들을 열어보니 esLint 관련 에러가 나는데 이건 제 환경 문제일까요?
