### ISSUE TITLE
[Help] 브랜치 커밋 관련.. 도움 요청합니다

### ISSUE THREAD

**Issue by jizerozz** [Dev-FE-1/Toy_Project_II_team4#71]
### 😢 문제 설명

1. .env 파일과 pdf 다운로드 기능을 같이 push 했던 원격 브랜치를 지움
2. 다시 main 브랜치로 checkout 후 새로운 브랜치를 만듦
3. 새로운 브랜치에서 이전에 작업한 다운로드 기능을 반영
4. 커밋하려고 보니 변경사항이 154개.. 일단 두 가지 파일만 추적하여 커밋시킴

이러한 상태인데 저희 원래 폴더구조에 .vite 폴더가 존재했었나요?..

### 🌐 문제 발생 상황

![image](https://github.com/user-attachments/assets/fdd31205-0ab2-4275-a7b2-22a03bd6c5a2)
![image](https://github.com/user-attachments/assets/6b937614-1777-4164-bf4d-b1f677ee4705)

상황은 위의 문제 설명에 올린 것과 같습니다..!

**Comment by red-dev-Mark** [comment]
저는 지금 확인해봤는데, `.vite`라는 폴더는 없어요!
그런데 저 수많은 mui icons들은 어디서 온걸까요...? ㅎ

**Comment by jizerozz** [comment]
그쵸?.................. ........ 왜 들어와진거지.......................

**Comment by jizerozz** [comment]
아직 병합은 안되어있는 상태고 pdf 폴더는 push해둔 상태라 pr 날려서 merge 하면 될 것 같아요! 제가... 좀 더 봐보고 pr 날리겠슴다..

**Comment by red-dev-Mark** [comment]
넵!~ ㅜㅜ

**Comment by nakyeonko3** [comment]
vite-icon들 다 삭제해도 될 것 같습니다.
vite 폴더가 안 들어가게 .gitignore에도 추가해둘게요. 근데 왜 저런일이 난건지 모르겠네요.
